// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc4nrSvrTUIfQyCRFb_Vds_m0yhzyKccY',
    appId: '1:196839652406:web:098389e47ef18227606c97',
    messagingSenderId: '196839652406',
    projectId: 'planora-ddf65',
    authDomain: 'planora-ddf65.firebaseapp.com',
    storageBucket: 'planora-ddf65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FPj0PKK_R69vrPuUCtiNqoJczY2E_A4',
    appId: '1:196839652406:android:08151119c3d55cdf606c97',
    messagingSenderId: '196839652406',
    projectId: 'planora-ddf65',
    storageBucket: 'planora-ddf65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBviqNdJ6d5DbAI2Qf2tSrEvWVAeO_N4s4',
    appId: '1:196839652406:ios:cfe3d0a290a32cd6606c97',
    messagingSenderId: '196839652406',
    projectId: 'planora-ddf65',
    storageBucket: 'planora-ddf65.firebasestorage.app',
    iosBundleId: 'com.example.planora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBviqNdJ6d5DbAI2Qf2tSrEvWVAeO_N4s4',
    appId: '1:196839652406:ios:cfe3d0a290a32cd6606c97',
    messagingSenderId: '196839652406',
    projectId: 'planora-ddf65',
    storageBucket: 'planora-ddf65.firebasestorage.app',
    iosBundleId: 'com.example.planora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc4nrSvrTUIfQyCRFb_Vds_m0yhzyKccY',
    appId: '1:196839652406:web:e9229d9183ef38ce606c97',
    messagingSenderId: '196839652406',
    projectId: 'planora-ddf65',
    authDomain: 'planora-ddf65.firebaseapp.com',
    storageBucket: 'planora-ddf65.firebasestorage.app',
  );
}
